name: crazydiskmark
version: 0.3.1
summary: Linux disk benchmark tool like CrystalDiskMark
description: |
  Crazy DiskMark is a utility to benchmark SSD disks on linux and produce results 
  like CrystalDiskMark.
base: core18
confinement: devmode


parts:
  crazydiskmark:
    plugin: python
    source: https://github.com/fredcox/crazydiskmark.git
    stage-packages:
      - python-six

apps:
  crazydiskmark:
    command: bin/crazydiskmark
